# SPDX-License-Identifier: GPL-3.0-or-later
cmake_minimum_required(VERSION 3.25.1)
find_package(CGAL 6.0 REQUIRED)
add_executable(mbm-cgal-repair main.cpp)
target_compile_features(mbm-cgal-repair PRIVATE cxx_std_17)
target_link_libraries(mbm-cgal-repair PRIVATE CGAL::CGAL)
install(TARGETS mbm-cgal-repair RUNTIME DESTINATION bin)
if(BUILD_TESTING)
    find_package(Python3 COMPONENTS Interpreter REQUIRED)
    if(TARGET mbm-cgal-planar)
        set(repair_test_planar $<TARGET_FILE:mbm-cgal-planar>)
    endif()
    add_test(NAME manifold_repair COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/test.py $<TARGET_FILE:mbm-cgal-repair> ${repair_test_planar})
endif()
